### ISSUE TITLE
Mobile responsive

### ISSUE THREAD

**Issue by AKprisonER** [sereneblue/coindexter#3]
Can you give any idea about  making it mobile responsive ?

**Comment by sereneblue** [comment]
I do intend to work on making coindexter mobile friendly when I have some time (soon).

I'll hide the sidebar on smaller screens. I'll model it so it's looks similar to [this](https://camo.githubusercontent.com/04832f41c7449c75331a20d82137a40b30995e84/68747470733a2f2f692e696d6775722e636f6d2f7254474b6d756a2e6a7067) but instead of the coin icons it'll be the indicator for the type of coin, and include the shift and wallet buttons.

**Comment by sereneblue** [comment]
I've added support for mobile devices to coindexter! https://github.com/sereneblue/coindexter/commit/66cc9b1fe7caf81444ebf3cf7140082f38b39a97

**Comment by AKprisonER** [comment]
in parallel i was also trying....Hopefully you got it

**Comment by AKprisonER** [comment]
Price, investment, settings are not available right ?

**Comment by AKprisonER** [comment]
Chrome browser/ Opera views are differing. S6 mobile view is fine. But chromium view still has Desktop like view with zoom in enabled

**Comment by sereneblue** [comment]
[This](https://raw.githubusercontent.com/sereneblue/coindexter/master/coindexter_mobile.png) is how it currently looks on a mobile device. I've degraded the experience for mobile devices. I used media queries so coindexter changes its view based on your screen's resolution (width).

You can view the 'mobile' view by changing the width of your desktop browser window.
